version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: carpadi-admin
    container_name: carpadi-admin
    restart: always
    ports:
      - 3000:3000
